def merek_keyboard():
    return [
        "Logitech",
        "Corsair",
        "Razer",
        "Komic",
        "SteelSeries",
        "HyperX",
        "Microsoft",
        "Apple",
        "ASUS",
        "Acer",
        "Dell",
        "HP",
        "NYK",
        "Robot",
        "Digital Alliance",
        "Lenovo",
        "Titan",
        "Rexus",
        "Royal Kludge",
        "Vortex",
        "Toshiba",
        "Cooler Master",
        "Keychron",
        "Ducky",
        "Varmilo",
        "Leopold",
        "Redragon",
        "Anne Pro",
        "Glorious",
        "Drop",
        "M-Tech",
        "Redragon",
        "Roccat",
        "Fantech",
        "Gigabyte",
        "Zowie",
        "Fnatic",
        "Azio",
        "Tt eSPORTS",
        "Mad Catz",
        "MSI",
        "AJAZZ",
    ]


def merek_mouse():
    return [
        "Logitech",
        "Razer",
        "Corsair",
        "SteelSeries",
        "HyperX",
        "Microsoft",
        "Apple",
        "ASUS",
        "Acer",
        "Rexus",
        "Dell",
        "HP",
        "Lenovo",
        "Cooler Master",
        "Zowie",
        "Glorious",
        "NYK",
        "Robot",
        "URGREEN",
        "JOYSEUS",
        "Genius",
        "iClever",
        "Genius",
        "M-Tech",
        "Unitech",
        "Mad Catz",
        "Roccat",
        "Gigabyte",
        "Fnatic",
        "Redragon",
        "Thermaltake",
        "Anker",
        "Trust",
        "EVGA",
        "BenQ",
        "Mionix",
        "Cougar",
        "G.Skill",
        "Patriot Viper",
        "Sabrent",
    ]


def merek_headphone():
    return [
        "Sony",
        "Logitech",
        "Samsung",
        "Apple",
        "Thinkplus",
        "Vivan",
        "Edifier",
        "Philips",
        "Nokia",
        "KRETZ",
        "Nakamichi",
        "JETE",
        "UGREEN",
        "Soundcore",
        "FiiO",
        "inBand",
        "Baseus",
        "Sades",
        "Cooler Master",
        "dbE",
        "Lenovo",
        "JBL",
        "Bose",
        "Sennheiser",
        "Audio-Technica",
        "Beats",
        "Skullcandy",
        "Jabra",
        "Marshall",
        "Beyerdynamic",
        "AKG",
        "Bang & Olufsen",
        "Shure",
        "Philips",
        "Pioneer",
        "Panasonic",
        "V-Moda",
        "Grado",
        "Master & Dynamic",
        "Bowers & Wilkins",
        "Klipsch",
        "Denon",
        "Focal",
        "Meze",
        "Hifiman",
    ]
