def merek_keyboard() -> list[str]:
    return [
        "Logitech",
        "Corsair",
        "Noir",
        "KiiP",
        "Inforce",
        "CLIPtec",
        "Zouya",
        "Razer",
        "Komic",
        "SteelSeries",
        "HyperX",
        "Microsoft",
        "Apple",
        "ASUS",
        "Acer",
        "Dell",
        "HP",
        "NYK",
        "Robot",
        "Digital Alliance",
        "Altec",
        "AULA",
        "Press Play",
        "dBE",
        "Divipard",
        "IdeaPad",
        "Armaggeddon",
        "CIDOO",
        "Alcatroz",
        "Lenovo",
        "Acome",
        "E-YOOSO",
        "Titan",
        "VENOMRX",
        "Sades",
        "Fantech",
        "Infinix",
        "M-Tech",
        "Switch",
        "Dark Alien",
        "ZIFRIEND",
        "Keycaps",
        "Paradox",
        "Dareu",
        "Rexus",
        "Royal Kludge",
        "Vortex",
        "Toshiba",
        "Cooler Master",
        "Keychron",
        "Ducky",
        "LEOBOG",
        "Varmilo",
        "Leopold",
        "Redragon",
        "Imperion",
        "VGN",
        "OLYPS",
        "Leopard",
        "Angry Miao",
        "Profftech",
        "Anne Pro",
        "Glorious",
        "Drop",
        "M-Tech",
        "Redragon",
        "Roccat",
        "Fantech",
        "Gigabyte",
        "Zowie",
        "Azio",
        "AJAZZ",
        "Tt eSPORTS",
        "Mad Catz",
        "MSI",
        "Fnatic",
        "",
    ]


def merek_mouse() -> list[str]:
    return [
        "Logitech",
        "Razer",
        "Corsair",
        "SteelSeries",
        "HyperX",
        "Microsoft",
        "Apple",
        "ASUS",
        "Acer",
        "Rexus",
        "Dell",
        "HP",
        "Lenovo",
        "Cooler Master",
        "Zowie",
        "Glorious",
        "NYK",
        "Robot",
        "Micropack",
        "Pinzy",
        "Mikuso",
        "Philips",
        "Delux",
        "Xiaomi",
        "Imperion",
        "Votre",
        "Vortex",
        "Goto",
        "Mpow",
        "MICLINK",
        "V106",
        "UGREEN",
        "RAPOO",
        "TaffWare",
        "Divipard",
        "Digital Alliance",
        "JOYSEUS",
        "HUAWEI",
        "MINISO",
        "Gidget",
        "Acome",
        "MOFii",
        "Unitech" "Alcatroz",
        "Fantech",
        "LAMZU",
        "8BitDo",
        "Switch",
        "Genius",
        "iClever",
        "Genius",
        "M-Tech",
        "Unitech",
        "Mad Catz",
        "Roccat",
        "Gigabyte",
        "Fnatic",
        "Redragon",
        "Thermaltake",
        "Anker",
        "Trust",
        "EVGA",
        "BenQ",
        "Mionix",
        "Cougar",
        "G.Skill",
        "Patriot Viper",
        "Sabrent",
        "",
    ]


def merek_headphone() -> list[str]:
    return [
        "Sony",
        "Logitech",
        "Samsung",
        "Apple",
        "Thinkplus",
        "Vivan",
        "Edifier",
        "Philips",
        "Nokia",
        "Audio Technica",
        "Mpow",
        "Superlux",
        "eZm,",
        "Rexus",
        "KIIP",
        "Suunto",
        "UFQ",
        "Robot",
        "Morejoy",
        "Shokz",
        "V Moda",
        "Takstar",
        "Klatre",
        "Acetech",
        "OneOdio",
        "TaffSTUDIO",
        "SoundPEATS",
        "Sharp",
        "Sonos",
        "ZOLA",
        "Moondrop",
        "Haylou",
        "XO",
        "HIFIMAN",
        "ACOME",
        "HUOREI",
        "U19",
        "P9",
        "iClever",
        "Dolphin",
        "BuddyPhones",
        "KREZT",
        "Naxen",
        "Nakamichi",
        "JETE",
        "UGREEN",
        "Soundcore",
        "FiiO",
        "inBand",
        "Baseus",
        "Sades",
        "Cooler Master",
        "dbE",
        "Lenovo",
        "JBL",
        "Bose",
        "Sennheiser",
        "Audio-Technica",
        "Beats",
        "Skullcandy",
        "Jabra",
        "Marshall",
        "Beyerdynamic",
        "AKG",
        "Bang & Olufsen",
        "Shure",
        "Philips",
        "Pioneer",
        "Panasonic",
        "V-Moda",
        "Grado",
        "Master & Dynamic",
        "Bowers & Wilkins",
        "Klipsch",
        "Denon",
        "Focal",
        "Meze",
        "Hifiman",
        "",
    ]


def merek_tas_laptop() -> list[str]:
    return [
        "Lenovo",
        "Ryota",
        "UGREEN",
        "HP",
        "MOVIO",
        "Remoid",
        "ASUS",
        "Carbon",
        "Sydney",
        "Fhea",
        "HAWEEL",
        "MINISO",
        "DNAC",
        "Mark Ryden",
        "WiWU",
        "Arctic Hunter",
        "Bange",
        "Venom",
        "M16",
        "Hima",
        "Savage",
        "Deli",
        "BASEUS",
        "Tictac",
        "Navy Club",
        "Huxley",
        "Alba Project",
        "KINMAC",
        "MAHOO",
        "Osprey",
        "Loops",
        "Norwich",
        "Bruno Cavalli",
        "SINNO",
        "Rhodey",
        "Huawei",
        "Fieri",
        "Haiden",
        "Aldier",
        "Oxford",
        "Freeknight",
        "Nylon",
        "Scratch",
        "Copenhagen",
        "Tomtoc",
        "ThinkPad",
        "Outwalk",
        "Brinch",
        "Itel",
        "Palazzo",
        "CopTon",
        "Martinversa",
        "Tumi",
        "Acer",
        "Large",
        "Lea",
        "Polo",
        "ABS",
        "Torch",
        "Apirilly",
        "Copper",
        "Rivacase",
        "Urban Factor",
        "Vention",
        "",
    ]


def merek_monitor() -> list[str]:
    return [
        "KOORUI",
        "Lenovo",
        "Samsung",
        "Touchindo",
        "Xiaomi",
        "SPC",
        "MSI",
        "BenQ",
        "LG",
        "Kerndy",
        "AOC",
        "Acer",
        "CUBE",
        "ViewSonic",
        "ASRock",
        "Dell",
        "Digital Alliance",
        "ASUS",
        "HP",
        "Enlight",
        "Aevision",
        "Armaggeddon",
        "Tecware",
        "Titan",
        "KKMOON",
        "Redmi",
        "Philips",
        "Fujitsu",
        "GOOJODOQ",
        "BEEX",
        "Dahua",
        "Gigabyte",
        "Magix",
        "Cooler Master",
        "Glenz",
        "",
    ]


def merek_speaker() -> list[str]:
    return [
        "Robot",
        "Kisonli",
        "JETE",
        "Edifier",
        "Fleco",
        "K-One",
        "Gamen",
        "Advance",
        "Ashley",
        "Gamen",
        "JBL",
        "Lenovo",
        "Bonks",
        "Altec",
        "Simbadda",
        "M-Tech",
        "Logitech",
        "Ezeey",
        "SADA",
        "Touchindo",
        "GMC",
        "Multimedia",
        "",
    ]


def merek_webcam() -> list[str]:
    return [
        "Eyesec",
        "Logitech",
        "Inforce",
        "Xiaovv",
        "Camtech",
        "M-Tech",
        "NYK",
        "Streamplify",
        "MOVIO",
        "Razer",
        "Anker",
        "Mibo",
        "ASUS",
        "SPC",
        "Noir",
        "Tecgear",
        "Philips",
        "MIXIO",
        "Lumi",
        "JETE",
        "Micropack",
        "Raptor",
        "Lenovo",
        "HikVision",
        "OBSBOT",
        "Ausdom",
        "Cisco",
        "Jabra",
        "Insta360",
        "Tenveo",
        "Televideo",
        "Brica",
        "KRX",
        "CLIPtec",
        "Rexus",
        "Digital Allience",
        "Komic",
        "Supermall",
        "iPason",
        "Hovercam",
        "AVerMedia",
        "Elgato",
        "Inbox",
        "Ashu",
        "Papalook",
        "Mycam",
        "",
    ]
